### PR TITLE
Add meal recommendation system backend with dining hall menu scraper …

### PR DESCRIPTION
**Pull request by ahmedar04**
Add comprehensive meal recommendation system for dining halls

This commit implements a complete meal recommendation system with the following components:

Backend:
- Web scraper for UMass dining hall menus using Puppeteer and Cheerio
- Express server with REST API endpoints for menu data
- Support for multiple dining locations (Worcester, Franklin, Hampshire, Berkshire)
- Menu parsing with nutritional info and dietary preferences

Frontend:
- Responsive UI with location and meal period selectors
- Advanced filtering system for dietary preferences (vegetarian, halal, etc.)
- Sourcing preferences (local, sustainable, antibiotic-free)
- Carbon rating system with visual indicators
- Real-time menu recommendations
- Detailed meal cards with nutritional stats and badges

Features:
- Automatic meal period detection based on time of day
- Dynamic loading states and error handling
- Accessibility improvements with ARIA labels
- Mobile-responsive design with UI adaptations
- UMass brand styling with custom color scheme

Technical Details:
- Server runs on port 4000
- CORS enabled for development
- Debug endpoints for testing
- Comprehensive error handling and logging
- CSS uses CSS custom properties for theming

### CODE REVIEW

**Comment by sshaik03** [comment]
looks good

**Comment by adithya-anand-999** [comment]
I like the details you provided in this message. I see that a lot of features have been added, this is good. In the future we would like to integrate this better with the overall app.

**Comment by adithya-anand-999** [comment]
this looks good, additional comment.

**Review by adithya-anand-999 — APPROVED** [review]
This looks good, in the future we would like to implement this better with the overall app. I feel like our app cant use all the features you have done here.

**Pull request merged**
